CREATE EXTENSION IF NOT EXISTS
    "uuid-ossp";
    
DROP TABLE IF EXISTS wiki_items;
DROP TABLE IF EXISTS notes;




CREATE TABLE wiki_items(
    id uuid DEFAULT uuid_generate_v4 (),
    wiki_title TEXT NOT NULL,
    content TEXT NOT NULL,
    keywords TEXT NOT NULL
    
);


CREATE TABLE notes (
    note_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subject TEXT NOT NULL,
    content TEXT NOT NULL, 
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

